name: Auto Commit

on:
  schedule:
    - cron: "10 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git Config
        run: |
          git config user.name "Tejomay Swain"
          git config user.email "tejomay3@gmail.com"

      - name: Make multiple commits
        run: |
          for i in {1..4}
          do
            echo "update $i $(date)" >> activity.txt
            git add .
            git commit -m "auto: update $i"
          done

      - name: Push changes
        run: |
          git push
